---
- name: Free disk space by deleting osbuild artifacts, unused containers and images
  gather_facts: true
  become: true
  hosts: image_builder

  tasks:

    - name: Delete finished composes
      ansible.builtin.shell: |
        set -o pipefail
        IFS=$'\n' read -r -d '' -a compose_arr <<< $(composer-cli compose list)
        for c in "${compose_arr[@]}"
        do
          composer-cli compose delete $(echo $c | awk -F' ' '{print $1}') || true
        done
      changed_when: false

    - name: Delete osbuild artifacts
      ansible.builtin.shell: |
        rm -rf /var/lib/osbuild-composer/artifacts/* 2> /dev/null || true;
        rm -rf /var/cache/osbuild-worker/osbuild-store/tmp/* 2> /dev/null || true;
        rm -rf /var/cache/osbuild-worker/osbuild-store/sources/org.osbuild.files/* 2> /dev/null || true
      changed_when: false
