---
- name: Free disk space by deleting osbuild artifacts, unused containers and images
  gather_facts: true
  hosts: image-builder

  vars:
    fdo_working_directory: "{{ ansible_env.HOME}}/fdo"

  tasks:
    - name: Delete downloaded images
      ansible.builtin.command: find {{ fdo_working_directory }} -type f \( -name "*.tar" -o -name "*.iso" \) -delete

    - name: Delete finished composes
      ansible.builtin.shell: |
        IFS=$'\n' read -r -d '' -a compose_arr <<< $(composer-cli compose list)
        for c in "${compose_arr[@]}"
        do
          composer-cli compose delete $(echo $c | awk -F' ' '{print $1}') || true
        done

    - name: Delete running containers
      ansible.builtin.shell: |
        IFS=$'\n' read -r -d '' -a container_arr <<< $(podman ps -a | grep "edge-container")
        for p in "${container_arr[@]}"
        do
          id=$(echo "$p" | awk -F' ' '{print $1}')
          podman stop $id
        done

    - name: Delete dangling container images
      ansible.builtin.shell: |
        IFS=$'\n' read -r -d '' -a img_arr <<< $(podman images | grep '<none>')
        for img in "${img_arr[@]}"
        do
           podman rmi $(echo "$img" | awk -F' ' '{print $3}')
        done

    - name: Delete osbuild artifacts
      ansible.builtin.shell: |
        rm -rf /var/lib/osbuild-composer/artifacts/* 2> /dev/null || true;
        rm -rf /var/cache/osbuild-worker/osbuild-store/tmp/* 2> /dev/null || true;
        rm -rf /var/cache/osbuild-worker/osbuild-store/sources/org.osbuild.files/* 2> /dev/null || true
