---
- name: Generate FDO keys and certificates
  hosts: certificate_generator
  become: true
  gather_facts: true

  tasks:
    - name: Generate and download keys and certificates
      ansible.builtin.import_role:
        name: keys_and_certificates
      vars:
        keys_and_certificates_dest: "{{ playbook_dir }}/keys/"
