---
- name: Generate an FDO-enabled RHEL for Edge simplified installer
  hosts: image_builder
  become: true
  gather_facts: true

  vars:
    compose_type: edge-simplified-installer

  tasks:
    # - name: Set up osbuild server
    #   ansible.builtin.include_role:
    #     name: infra.osbuild.setup_server

    # - name: Build FDO-enabled simplified installer image
    #   ansible.builtin.include_role:
    #     name: infra.osbuild.builder
    #   vars:
    #     builder_compose_type: "{{ compose_type }}"
    #     builder_blueprint_name: "{{ blueprint_name }}"
    #     builder_compose_customizations:
    #       installation_device: /dev/vda
    #       fdo:
    #         manufacturing_server_url: "http://{{ manufacturing_server_host }}:8080"
    #         diun_pub_key_insecure: "true"
    #     builder_compose_pkgs: []

    - name: Download latest installer image to local host
      ansible.builtin.include_role:
        name: latest_installer
      vars:
        latest_installer_blueprint_name: "{{ blueprint_name }}"
        latest_installer_compose_type: "{{ compose_type }}"
        latest_installer_dest: "{{ playbook_dir }}"
      when: download_image | bool | default(false)
