---
- name: Set common server variables
  gather_facts: true
  hosts:
    - keys-generator
    - manufacturing
    - owner-onboarding
    - rendezvous
    - serviceinfo-api

  tasks:
    - ansible.builtin.set_fact:
        fdo_working_directory: "{{ ansible_env.HOME}}/fdo"
        shared_keys_directory: "{{ playbook_dir }}/keys"
        remote_keys: false

- name: Generate keys/certificates and copy to a shared directory
  gather_facts: false
  hosts: keys-generator

  pre_tasks:
    - ansible.builtin.set_fact:
        keys_directory: "{{ fdo_working_directory }}/keys"

  roles:
    - role: cryptographic_keys

  tasks:
    - name: Ensure that the shared keys directory exists
      ansible.builtin.file:
        path: "{{ shared_keys_directory }}"
        state: directory
      delegate_to: localhost

    - name: List keys/certificates
      ansible.builtin.find:
        paths: "{{ keys_directory }}"
        recurse: no
      register: _key_files
      delegate_to: keys-generator

    - name: Copy generated keys/certificates into the shared directory
      ansible.builtin.fetch:
        src: "{{ item }}"
        dest: "{{ shared_keys_directory }}/"
        flat: true
      with_items: "{{ _key_files | community.general.json_query('files[*].path') }}"

- name: Set up manufacturing server
  gather_facts: false
  hosts: manufacturing

  roles:
    - role: server_setup
      vars:
        component_name: manufacturing-server
        rendezvous_host: "{{ hostvars['rendezvous'].ansible_host | default(hostvars['rendezvous'].inventory_hostname) }}"
        subdirectories:
          - manufacturing_sessions
          - owner_vouchers
          - manufacturer_keys
        keys:
          - diun_key.der
          - diun_cert.pem
          - manufacturer_cert.pem
          - manufacturer_key.der
          - owner_cert.pem
          - device_ca_key.der
          - device_ca_cert.pem
        keys_directory: "{{ shared_keys_directory }}"

- name: Set up rendezvous server
  gather_facts: false
  hosts: rendezvous
  roles:
    - role: server_setup
      vars:
        component_name: rendezvous-server
        subdirectories:
          - rendezvous_registered
          - rendezvous_sessions
        keys:
          - manufacturer_cert.pem
        keys_directory: "{{ shared_keys_directory }}"

- name: Set up serviceinfo-api server
  gather_facts: true
  hosts: serviceinfo-api

  pre_tasks:
    - ansible.builtin.set_fact:
        serviceinfo_api_token: "{{ lookup('ansible.builtin.password', '/dev/null') }}"
        serviceinfo_api_admin_token: "{{ lookup('ansible.builtin.password', '/dev/null') }}"

  roles:
    - role: server_setup
      vars:
        component_name: serviceinfo-api-server
        packages:
          - fdo-owner-onboarding-server
        # This is an example of service info injected into a device on onboarding
        service_info: |
          initial_user:
            username: admin
            sshkeys:
            - "{{ lookup('file', admin_ssh_key_file )}}"
          files:
          - path: /root/resolv.conf
            source_path: /etc/resolv.conf
          commands:
          - command: touch
            args:
            - /root/test
            return_stdout: true
            return_stderr: true
          diskencryption_clevis:
          - disk_label: /dev/vda4
            binding:
              pin: tpm2
              config: "{}"
            reencrypt: true
          additional_serviceinfo: ~
        subdirectories:
          - device_specific_serviceinfo
        keys_directory: "{{ shared_keys_directory }}"

- name: Set up owner-onboarding server
  gather_facts: true
  hosts: owner-onboarding
  roles:
    - role: server_setup
      vars:
        component_name: owner-onboarding-server
        serviceinfo_api_host: "{{ hostvars['serviceinfo-api'].ansible_host | default(hostvars['serviceinfo-api'].inventory_hostname) }}"
        serviceinfo_api_token: "{{ hostvars['serviceinfo-api'].serviceinfo_api_token }}"
        owner_host: "{{ hostvars['owner-onboarding'].ansible_host | default(hostvars['owner-onboarding'].inventory_hostname) }}"
        subdirectories:
          - owner_onboarding_sessions
          - owner_vouchers
        keys:
          - device_ca_cert.pem
          - owner_key.der
          - owner_cert.pem
        keys_directory: "{{ shared_keys_directory }}"
