---
- name: Generate an FDO-enabled RHEL for Edge image
  hosts: image_builder
  become: true
  gather_facts: true

  vars:
    manufacturing_server_url: "http://{{ manufacturing_server_host }}:8080"
    diun_pub_key_insecure: true
    installation_device: /dev/vda

  tasks:
    - name: Set up OSBuild server
      ansible.builtin.import_role:
        name: infra.osbuild.setup_server

    - name: Build base RHEL for Edge image
      ansible.builtin.import_role:
        name: infra.osbuild.builder
      vars:
        builder_compose_type: edge-commit
        builder_blueprint_name: rhel-for-edge
        builder_compose_customizations: {}
        builder_compose_pkgs: []
