---
- name: Generate an FDO-enabled RHEL for Edge simplified installer
  hosts: image_builder
  become: true
  gather_facts: true

  vars:
    installation_device: /dev/vda
    builder_blueprint_name: fdo-demo

  tasks:
    - name: Set up osbuild server
      ansible.builtin.import_role:
        name: infra.osbuild.setup_server

    - name: Build FDO-enabled simplified installer image
      ansible.builtin.import_role:
        name: infra.osbuild.builder
      vars:
        builder_compose_type: edge-simplified-installer
        builder_compose_customizations:
          installation_device: "{{ installation_device }}"
          fdo:
            manufacturing_server_url: "http://{{ manufacturing_server_host }}:8080"
            diun_pub_key_insecure: "true"
        builder_compose_pkgs: []

    - name: Download latest installer image to local host
      ansible.posix.synchronize:
        dest: "{{ playbook_dir }}"
        src: "{{ builder_image_path }}"
        mode: pull
      when: download_image | bool | default(false)
