- name: Set up manufacturing_server
  hosts: manufacturing_server
  become: true
  gather_facts: true
  roles:
  - community.fdo.setup_manufacturing_server
  - community.fdo.configure_manufacturing_server

- name: Set up rendezvous server
  hosts: rendezvous_server
  become: true
  gather_facts: true
  roles:
  - community.fdo.setup_rendezvous_server
  - community.fdo.configure_rendezvous_server

- name: Set up owner server
  hosts: owner_server
  become: true
  gather_facts: true
  roles:
  - community.fdo.setup_owner_server
  - community.fdo.configure_owner_server
