---
- name: Generate an FDO-enabled RHEL for Edge simplified installer
  hosts: image_builder
  become: true
  gather_facts: true

  tasks:
    - name: Set up osbuild server
      ansible.builtin.import_role:
        name: infra.osbuild.setup_server

    - name: Build base RHEL for Edge image
      ansible.builtin.import_role:
        name: infra.osbuild.builder
      vars:
        builder_compose_type: edge-commit
        builder_blueprint_name: rhel-for-edge
        builder_compose_customizations: {}
        builder_compose_pkgs: []

    #####################################################
    # THIS PART ISN'T CURRENTLY WORKING AS EXPECTED
    # It produces an edge-commit instead of an edge-simplified-installer.
    # In order to create a simplified installer manually,
    # push the blueprint (e.g. fdo-rhel-for-edge-simplified) and run
    # on the image_builder host:
    # composer-cli compose start-ostree fdo-rhel-for-edge-simplified \
    #   edge-simplified-installer \
    #   --ref rhel/9/x86_64/edge \
    #   --url http://localhost/rhel-for-edge/repo/
    #####################################################
    # - name: Build FDO-enabled RHEL for Edge image
    #   ansible.builtin.import_role:
    #     name: infra.osbuild.builder
    #   vars:
    #     # use the default value for builder_blueprint_ref
    #     builder_compose_type: edge-simplified-installer
    #     builder_blueprint_name: fdo-rhel-for-edge-simplified
    #     manufacturing_server: "{{ groups['manufacturing_server'][0] }}"
    #     manufacturing_server_host: "{{ hostvars[manufacturing_server].ansible_host | default(hostvars[manufacturing_server].inventory_hostname) }}"
    #     builder_compose_customizations:
    #       installation_device: /dev/vda
    #       fdo:
    #         manufacturing_server_url: "http://{{ manufacturing_server_host }}:8080"
    #         diun_pub_key_insecure: "true"
    #     builder_compose_pkgs: []
