- name: Ensure output directory exists
  ansible.builtin.file:
    path: "{{ keys_directory }}"
    state: directory

- name: Install required packages
  ansible.builtin.package:
    name: fdo-admin-cli
    state: present

- name: Generate keys
  ansible.builtin.command: |
    fdo-admin-tool generate-key-and-cert \
      --organization '{{ certificate_org }}' \
      --country {{ certificate_country }} \
      --destination-dir '{{ keys_directory }}' \
      {{ item }}
  with_items:
    - diun
    - manufacturer
    - device-ca
    - owner
