- name: Ensure registries directory exists
  ansible.builtin.file:
    path: "{{ serviceinfo_api_storage_dir }}/registries.conf.d"
    state: directory

- name: Create registry entry
  ansible.builtin.template:
    src: registries.j2
    dest: "{{ serviceinfo_api_storage_dir }}/registries.conf.d/003-r4e.conf"

- name: Ensure script directory
  ansible.builtin.file:
    path: "{{ serviceinfo_api_storage_dir }}/scripts"
    state: directory

- name: Create switch script
  ansible.builtin.copy:
    src: container-switch.sh
    dest: "{{ serviceinfo_api_storage_dir }}/scripts/container-switch.sh"
