- name: Create RHEL for Edge base blueprint
  ansible.builtin.template:
    src: rhel4edge-blueprint.toml.j2
    dest: "{{ fdo_working_directory }}/rhel4edge-blueprint.toml"
  vars:
    ssh_key: "{{ lookup('file', root_ssh_key_file) }}"
    password: "{{ admin_password | password_hash('sha512') }}"

- name: Push the RHEL for Edge base blueprint
  ansible.builtin.command: composer-cli blueprints push {{ fdo_working_directory }}/rhel4edge-blueprint.toml

- name: Start RHEL for Edge base commit compose
  ansible.builtin.command: composer-cli compose start-ostree rhel-for-edge-iso edge-container -j
  register: _base_compose_output

- ansible.builtin.set_fact:
    base_compose_id: "{{ _base_compose_output.stdout | from_json | community.general.json_query('body.build_id')}}"

- name: Wait for the compose {{ base_compose_id }} to finish
  ansible.builtin.shell: composer-cli compose status | grep {{ base_compose_id }} | awk '{print $2}'
  register: _compose_status_output
  until: _compose_status_output.stdout in ["FINISHED", "FAILED"]
  delay: 30
  retries: 60

- name: Download the base image
  ansible.builtin.command: composer-cli compose image {{ base_compose_id }}
  args:
    chdir: "{{ fdo_working_directory }}"

- ansible.builtin.set_fact:
    base_image_file: "{{ base_compose_id }}-container.tar"
